# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: ifoodapp
services:
  consul:
    extends:
      file: ./consul.yml
      service: consul
  consul-config-loader:
    extends:
      file: ./consul.yml
      service: consul-config-loader
